apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: productpage-ratelimit
    descriptors:
      - key: HEADER
        value: "0d805df0-6e18-4916-84ab-7446a1ca401b"
        rate_limit:
          unit: second
          requests_per_unit: 2
      - key: HEADER
        rate_limit:
          unit: second
          requests_per_unit: 5
